package proyecto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class MenuUserAlquilar extends javax.swing.JInternalFrame {

    private Connection connection = null;
    private ResultSet rs = null;
    private Statement s = null;
    public String user = "";
    
    public MenuUserAlquilar() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        llenarCombos();
    }
    
    private void llenar(String nombreTabla, JComboBox combo, String idNombre){
        Conexion();
        try{
            s = connection.createStatement();
            rs = s.executeQuery("SELECT * FROM "+nombreTabla+" ");
            
            while(rs.next()){   
                combo.addItem(rs.getString(idNombre));
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Archivo no encontrado " + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void llenarCombos(){
        llenar("\"vehiculo\" WHERE \"estado\" = 't'", cmbPlacas, "placa");
        llenar("\"oficinas\"", cmbOficinasR, "id_oficina");
        llenar("\"oficinas\"", cmbOficinasD, "id_oficina");
    }

    public void Conexion() {
        if (connection != null) {
            return;
        }

        String url = "jdbc:postgresql://localhost:5432/postgres";
        String password = "123";
        try {
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection(url, "postgres", password);
            if (connection != null) {
                System.out.println("Connecting to database...");
            }
        } catch (Exception e) {
            System.out.println("Problem when connecting to the database");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbPlacas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHoraR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbOficinasR = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        cmbOficinasD = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHoraD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFechaD = new javax.swing.JTextField();
        btnAlquilar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jchkGPS = new javax.swing.JCheckBox();
        jchkBoos = new javax.swing.JCheckBox();
        jchkBebe = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Alquilar Vehículo");

        jLabel1.setText("Placa del vehículo: ");

        cmbPlacas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Placas>" }));
        cmbPlacas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPlacasItemStateChanged(evt);
            }
        });

        jLabel2.setText("Retirar");

        jLabel3.setText("Oficina: ");

        jLabel4.setText("Fecha: ");

        jLabel5.setText("Hora: ");

        jLabel6.setText("(24hrs)");

        jLabel7.setText("(00-00-0000)");

        cmbOficinasR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Oficinas>" }));

        jLabel8.setText("(00-00-0000)");

        cmbOficinasD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Oficinas>" }));

        jLabel9.setText("Devolucion");

        jLabel10.setText("Oficina: ");

        jLabel11.setText("Fecha: ");

        jLabel12.setText("Hora: ");

        jLabel13.setText("(24hrs)");

        btnAlquilar.setText("Alquilar");
        btnAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlquilarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jInternalFrame1.setTitle("Extras");
        jInternalFrame1.setVisible(true);

        jchkGPS.setText("GPS ($9)");
        jchkGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkGPSActionPerformed(evt);
            }
        });

        jchkBoos.setText("Booster ($11)");
        jchkBoos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkBoosActionPerformed(evt);
            }
        });

        jchkBebe.setText("Silla para bebés ($3)");
        jchkBebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkBebeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkGPS)
                    .addComponent(jchkBoos)
                    .addComponent(jchkBebe))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchkGPS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jchkBoos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkBebe)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel14.setText("Total: ");

        txtTotal.setEditable(false);
        txtTotal.setText("0");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtFechaR)
                                            .addComponent(txtHoraR)
                                            .addComponent(cmbOficinasR, 0, 122, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(186, 186, 186)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel12)
                                                        .addGap(29, 29, 29))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtFechaD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel8))
                                                .addComponent(cmbOficinasD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtHoraD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel13))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnAlquilar)
                                            .addGap(118, 118, 118)
                                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(1, 1, 1)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(cmbPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(cmbOficinasR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFechaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtHoraR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbOficinasD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtFechaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHoraD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlquilar)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAlquilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlquilarActionPerformed
        // TODO add your handling code here:
        if(combosSele()){
            Conexion();
            try{
                
                int placa = Integer.parseInt(cmbPlacas.getSelectedItem().toString());
                int idUser = Integer.parseInt(this.user.split("-")[0]);
                String nombreUser = this.user.split("-")[1];
                int oficinaR = Integer.parseInt(cmbOficinasR.getSelectedItem().toString());
                String fechaR = txtFechaR.getText();
                int horaR = Integer.parseInt(txtHoraR.getText());
                int oficinaD = Integer.parseInt(cmbOficinasD.getSelectedItem().toString());
                String fechaD = txtFechaD.getText();
                int horaD = Integer.parseInt(txtHoraD.getText());
                float precio = Float.parseFloat(txtTotal.getText());

                s = connection.createStatement();
                int z = s.executeUpdate("INSERT INTO alquiler_vehiculos (\"placa_vehiculo\", \"id_usuario\", \"nombre_usuario\"," +
"                                                                        \"oficina_retiro\", \"oficina_devolucion\", \"fecha_retiro\"," +
"                                                                        \"hora_retiro\", \"fecha_devolucion\", \"hora_devolucion\", \"precio_alquiler\")"
                                                              + "VALUES ('"+placa+"','"+idUser+"','"+nombreUser+"',"
                                                                      +  "'"+oficinaR+"', '"+oficinaD+"', '"+fechaR+"',"
                                                                       + "'"+horaR+"', '"+fechaD+"', '"+horaD+"', '"+precio+"')");
                
                
                
                s = connection.createStatement();
                z = s.executeUpdate("UPDATE vehiculo SET \"estado\" = 'f' WHERE \"placa\" = '"+placa+"'");
                
                if (z == 1) {
                    JOptionPane.showMessageDialog(null, "Alquiler de vehículo completado", "Alquiler", JOptionPane.DEFAULT_OPTION);
                } else {
                    JOptionPane.showMessageDialog(null, "Alquiler de vehículo interrumpido", "Error", JOptionPane.DEFAULT_OPTION);
                }
                

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Archivo no encontrado " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar las oficinas y un vehiculo.", "Error",JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();       
    }//GEN-LAST:event_btnAlquilarActionPerformed

    private void jchkGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkGPSActionPerformed
        // TODO add your handling code here:
        if(jchkGPS.isSelected()){
            float total =  Float.parseFloat(txtTotal.getText());
            txtTotal.setText(String.valueOf(total + 9));
        }else{
            float total =  Float.parseFloat(txtTotal.getText());
            txtTotal.setText(String.valueOf(total - 9));
        }
    }//GEN-LAST:event_jchkGPSActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void jchkBoosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkBoosActionPerformed
        // TODO add your handling code here:
        if(jchkBoos.isSelected()){
            float total =  Float.parseFloat(txtTotal.getText());
            txtTotal.setText(String.valueOf(total + 11));
        }else{
            float total =  Float.parseFloat(txtTotal.getText());
            txtTotal.setText(String.valueOf(total - 11));
        }
    }//GEN-LAST:event_jchkBoosActionPerformed

    private void jchkBebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkBebeActionPerformed
        // TODO add your handling code here:
        if(jchkBebe.isSelected()){
            float total =  Float.parseFloat(txtTotal.getText());
            txtTotal.setText(String.valueOf(total + 3));
        }else{
            float total =  Float.parseFloat(txtTotal.getText());
            txtTotal.setText(String.valueOf(total - 3));
        }
    }//GEN-LAST:event_jchkBebeActionPerformed

    private void limpiar(){
        cmbOficinasR.setSelectedIndex(0);
        txtFechaR.setText(null);
        txtHoraR.setText(null);
        
        cmbOficinasD.setSelectedIndex(0);
        txtFechaD.setText(null);
        txtHoraR.setText(null);
        
        txtTotal.setText("0");
        
        jchkGPS.setSelected(false);
        jchkBoos.setSelected(false);
        jchkBebe.setSelected(false);
        
    }
    
    private void cmbPlacasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPlacasItemStateChanged
        // TODO add your handling code here:
        txtTotal.setText("0");
        if(cmbPlacas.getSelectedIndex() == 0){
            limpiar();
        }else{
            Conexion();
            try{
                String placa = cmbPlacas.getSelectedItem().toString();
                s = connection.createStatement();
                rs = s.executeQuery("SELECT * FROM \"vehiculo\" WHERE \"placa\" = '"+placa+"'");
                
                while(rs.next()){
                    float total =  Float.parseFloat(txtTotal.getText());
                    float precio = Float.parseFloat(rs.getString("precio"));
                    txtTotal.setText(String.valueOf(total + precio));
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Archivo no encontrado " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmbPlacasItemStateChanged

    private boolean combosSele(){
        boolean bandera = true;
        if(cmbPlacas.getSelectedIndex() == 0 || 
           cmbOficinasR.getSelectedIndex() == 0 ||
           cmbOficinasD.getSelectedIndex() == 0){
            bandera = false;
        }
        return bandera;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlquilar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbOficinasD;
    private javax.swing.JComboBox<String> cmbOficinasR;
    private javax.swing.JComboBox<String> cmbPlacas;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox jchkBebe;
    private javax.swing.JCheckBox jchkBoos;
    private javax.swing.JCheckBox jchkGPS;
    private javax.swing.JTextField txtFechaD;
    private javax.swing.JTextField txtFechaR;
    private javax.swing.JTextField txtHoraD;
    private javax.swing.JTextField txtHoraR;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
